spring.application.name=yacht-catalog-service

# Setam portul pe care va rula acest serviciu
server.port=8081

# Activam consola H2 ca sa putem vedea baza de date din browser (optional, dar util)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:yachtdb
