trigger:
  branches:
    include:
      - main
      - master

pool:
  # Folosim un agent gratuit de la Microsoft cu Ubuntu (sau poți pune numele agentului tău local dacă ai făcut Section 5 din lab)
  vmImage: 'ubuntu-latest'

steps:
  # ─── BUILD & TEST: YACHT CATALOG SERVICE ───────────────────────
  - task: Maven@4
    displayName: 'Build & Test Yacht Catalog Service'
    inputs:
      mavenPomFile: 'yacht-catalog-service/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'

  # ─── BUILD & TEST: ORDER SERVICE ───────────────────────────────
  - task: Maven@4
    displayName: 'Build & Test Order Service'
    inputs:
      mavenPomFile: 'order-service/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'